### ISSUE TITLE
Unenrol me from course for student is not available

### ISSUE THREAD

**Issue by ZanikaAdleena** [3ilogiclms/moodle-theme_contemporary#11]
I read it somewhere that course administration block is not available anymore to students. In the course administration block, student can unenrol themselves if they accidentally enrol to the wrong course. For your information, when I used another theme, the link unenrol me from course is exist. But not in the contemporary theme. I also already tried to change in the role permissions settings. But this way also did not work. 

I hope that your team will fix this issues.

**Comment by 3ilogiclms** [comment]
Dear Zanika,

Thank you for query that you raised. We'll work on it and update you. It will better if you share your email address so that we can send you changes file earlier before update on github or on Moodle community. You can directly reach us too at lms@3ilogic.com

Thank you,
3i Logic LMS Support Team

**Comment by ZanikaAdleena** [comment]
Sure, you can contact me through this email address on any update later.

**Comment by ZanikaAdleena** [comment]
Dear 3ilogiclms, 

Sorry for the inconvenient. Somehow, I hide the administration block from student view and that's why they cannot view for course administration block. Thank you for your response.
